# SPDX-FileCopyrightText: 2025 Dom Rodriguez <shymega@shymega.org.uk>
#
# SPDX-License-Identifier: GPL-3.0-only

---
name: Nix packaging tests

on:
  push:
    paths:
      - 'flake.nix'
      - 'default.nix'
      - 'shell.nix'
      - '.github/workflows/ci-builds.yml'
      - 'src/**'
      - 'packages/**'
      - 'devshell.nix'
  pull_request:
    paths:
      - 'flake.nix'
      - 'default.nix'
      - 'shell.nix'
      - '.github/workflows/ci-builds.yml'
      - 'src/**'
      - 'packages/**'
      - 'devshell.nix'

jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake check --show-trace --impure --print-build-logs --accept-flake-config

  check-nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build github:srid/devour-flake --impure -L --no-link --print-out-paths --override-input flake "$GITHUB_WORKSPACE"
